##################################################
## Project: Cancer Hallmarks
## Script purpose: Variables with metadata and full names for hallmarks and samples
## Author: Sergi Cervilla* & Mustafa Sibai*
##################################################

#Complete hallmark names
color_codes <-  list("Sustaining Proliferative Signaling"="#15CE59", 
                     "Evading Growth Suppressors" = "#701717",
                     "Avoiding Immune Destruction" = "#CB3BBD",
                     "Enabling Replicative Immortality" = "#4969D4",
                     "Tumor-Promoting Inflammation" = "#E6880D",
                     "Activating Invasion and Metastasis" = "#000000",
                     "Inducing Angiogenesis" = "#EE0F16",
                     "Genome Instability and Mutation" = "#132892",
                     "Resisting Cell Death" = "#8E909B",
                     "Deregulating Cellular Energetics" = "#71189E",
                     "Senescent cells" = "#05F3EB",
                     "Nonmutational Epigenetic reprogramming" = "#890269",
                     "Unlocking Phenotypic Plasticity" = "#95641A")
hallmark_names <- c("Sustaining Proliferative Signaling", 
                    "Evading Growth Suppressors",
                    "Avoiding Immune Destruction",
                    "Enabling Replicative Immortality",
                    "Tumor-Promoting Inflammation",
                    "Activating Invasion and Metastasis",
                    "Inducing Angiogenesis",
                    "Genome Instability and Mutation",
                    "Resisting Cell Death",
                    "Deregulating Cellular Energetics",
                    "Senescent cells",
                    "Nonmutational Epigenetic reprogramming",
                    "Unlocking Phenotypic Plasticity")

hallmark_names_list <- list("H1" = "Sustaining Proliferative Signaling", 
                       "H2" = "Evading Growth Suppressors",
                       "H3" = "Avoiding Immune Destruction",
                       "H4" = "Enabling Replicative Immortality",
                       "H5" = "Tumor-Promoting Inflammation",
                       "H6" = "Activating Invasion and Metastasis",
                       "H7" = "Inducing Angiogenesis",
                       "H8" = "Genome Instability and Mutation",
                       "H9" = "Resisting Cell Death",
                       "H10" = "Deregulating Cellular Energetics",
                       "H11" = "Senescent cells",
                       "H12" = "Nonmutational Epigenetic reprogramming",
                       "H13" = "Unlocking Phenotypic Plasticity")



annotation_method <- list("Breast1" = "OCT",
                          "Breast3" = "OCT",
                          "Prostate2" = "FFPE",
                          "Ovarian3" = "OCT",
                          "Prostate1" = "FFPE",
                          "Colorectal5" = "OCT",
                          "Glioblastoma1" = "OCT",
                          "Ovarian1" = "OCT",
                          "Colorectal8" = "OCT",
                          "Ovarian5" = "FFPE",
                          "Breast4" = "FFPE",
                          "Liver5" = "FFPE",
                          "Liver1" = "OCT",
                          "Liver2" ="OCT",
                          "BreastA" ="OCT",
                          "Breast9" ="OCT",
                          "Ovarian2" ="FFPE",
                          "Ovarian4" = "FFPE",
                          "Liver3" = "OCT",
                          "Colorectal6" = "OCT",
                          "Liver4" = "OCT",
                          "Colorectal7" = "OCT",
                          "Bladder1" = "FFPE",
                          "Bladder2" = "FFPE",
                          "Bladder3" = "FFPE",
                          "Bladder4" = "FFPE",
                          "Bladder5" = "FFPE",
                          "Kidney5" = "FFPE",
                          "Kidney1" = "FFPE",
                          "Kidney2" = "FFPE",
                          "Kidney3" = "FFPE",
                          "Kidney4" = "FFPE",
                          "Pancreas1" = "OCT",
                          "Pancreas2" = "OCT",
                          "Pancreas3" = "OCT",
                          "Pancreas4" = "OCT",
                          "Pancreas5" = "OCT",
                          "Glioblastoma2" = "OCT",
                          "Glioblastoma3" = "OCT",
                          "Glioblastoma4" = "OCT",
                          "Glioblastoma5" = "OCT",
                          "Colorectal1" = "FFPE",
                          "Colorectal2" = "FFPE",
                          "Colorectal3" = "FFPE",
                          "Colorectal4" = "FFPE",
                          "Breast5" = "FFPE",
                          "Breast6" = "FFPE",
                          "Breast7" = "FFPE",
                          "Breast8" = "FFPE",
                          "Lung1" = "FFPE",
                          "Lung2" = "FFPE",
                          "Lung3" = "FFPE",
                          "Lung4" = "FFPE",
                          "Lung5" = "FFPE",
                          "Lung6" = "FFPE",
                          "Lung7" = "FFPE",
                          "Prostate3" = "OCT",
                          "Prostate4" = "OCT"
                          
)


annotation_generated <- list("Breast" = "Public",
                          "Breast3" = "Public",
                          "Prostate2" = "Public",
                          "Ovarian3" = "Public",
                          "Prostate1" = "Public",
                          "Colorectal5" = "Public",
                          "Glioblastoma1" = "Public",
                          "Ovarian1" = "In-House",
                          "Colorectal8" = "Public",
                          "Ovarian5" = "Public",
                          "Breast4" = "Public",
                          "Liver5" = "Public",
                          "Liver1" = "Public",
                          "Liver2" ="Public",
                          "BreastA" ="Public",
                          "Breast9" ="Public",
                          "Ovarian4" = "Public",
                          "Liver3" = "Public",
                          "Ovarian2" ="In-House",
                          "Colorectal6" = "Public",
                          "Liver4" = "Public",
                          "Colorectal7" = "Public",
                          "Bladder1" = "In-House",
                          "Bladder2" = "In-House",
                          "Bladder3" = "In-House",
                          "Bladder4" = "In-House",
                          "Bladder5" = "In-House",
                          "Kidney5" = "Public",
                          "Kidney1" = "Public",
                          "Kidney2" = "Public",
                          "Kidney3" = "Public",
                          "Kidney4" = "Public",
                          "Pancreas1" = "Public",
                          "Pancreas2" = "Public",
                          "Pancreas3" = "Public",
                          "Pancreas4" = "Public",
                          "Pancreas5" = "Public",
                          "Glioblastoma2" = "Public",
                          "Glioblastoma3" = "Public",
                          "Glioblastoma4" = "Public",
                          "Glioblastoma5" = "Public",
                          "Colorectal1" = "In-House",
                          "Colorectal2" = "In-House",
                          "Colorectal3" = "In-House",
                          "Colorectal4" = "In-House",
                          "Breast5" = "In-House",
                          "Breast6" = "In-House",
                          "Breast7" = "In-House",
                          "Breast8" = "In-House",
                          "Lung1" = "In-House",
                          "Lung2" = "In-House",
                          "Lung3" = "In-House",
                          "Lung4" = "In-House",
                          "Lung5" = "In-House",
                          "Lung6" = "In-House",
                          "Lung7" = "In-House",
                          "Prostate3" = "Public",
                          "Prostate4" = "Public"
)

annotation_site <- list("Breast" = "Breast (n=9)",
                        "Breast3" = "Breast (n=9)",
                        "Ovarian3" = "Ovary (n=5)",
                        "Colorectal5" = "Colorectal (n=8)",
                        "Ovarian1" = "Ovary (n=5)",
                        "Colorectal8" = "Colorectal (n=8)",
                        "Ovarian5" = "Ovary (n=5)",
                        "Breast4" = "Breast (n=9)",
                        "Liver5" = "Liver (n=5)",
                        "Liver1" = "Liver (n=5)",
                        "Liver2" ="Liver (n=5)",
                        "BreastA" ="Breast (n=9)",
                        "Breast9" ="Breast (n=9)",
                        "Ovarian4" = "Ovary (n=5)",
                        "Liver3" = "Liver (n=5)",
                        "Colorectal6" = "Colorectal (n=8)",
                        "Liver4" = "Liver (n=5)",
                        "Colorectal7" = "Colorectal (n=8)",
                        "Bladder1" = "Bladder (n=5)",
                        "Bladder2" = "Bladder (n=5)",
                        "Bladder3" = "Bladder (n=5)",
                        "Bladder4" = "Bladder (n=5)",
                        "Bladder5" = "Bladder (n=5)",
                        "Kidney5" = "Kidney (n=5)",
                        "Kidney1" = "Kidney (n=5)",
                        "Kidney2" = "Kidney (n=5)",
                        "Kidney3" = "Kidney (n=5)",
                        "Kidney4" = "Kidney (n=5)",
                        "P259_H1A2" = "Pancreas (n=5)",
                        "Pancreas2" = "Pancreas (n=5)",
                        "Pancreas3" = "Pancreas (n=5)",
                        "Pancreas4" = "Pancreas (n=5)",
                        "Pancreas5" = "Pancreas (n=5)",
                        "Glioblastoma2" = "Glioblastoma (n=5)",
                        "Glioblastoma3" = "Glioblastoma (n=5)",
                        "Glioblastoma4" = "Glioblastoma (n=5)",
                        "Glioblastoma5" = "Glioblastoma (n=5)",
                        "Glioblastoma1" = "Glioblastoma (n=5)",
                        "Prostate2" = "Prostate (n=4)",
                        "Prostate1" = "Prostate (n=4)",
                        "Colorectal1" = "Colorectal (n=8)",
                        "Colorectal2" = "Colorectal (n=8)",
                        "Colorectal3" = "Colorectal (n=8)",
                        "Colorectal4" = "Colorectal (n=8)",
                        "Breast5" = "Breast (n=9)",
                        "Breast6" = "Breast (n=9)",
                        "Breast7" = "Breast (n=9)",
                        "Breast8" = "Breast (n=9)",
                        "Lung1" = "Lung (n=7)",
                        "Lung2" = "Lung (n=7)",
                        "Lung3" = "Lung (n=7)",
                        "Lung4" = "Lung (n=7)",
                        "Lung5" = "Lung (n=7)",
                        "Lung6" = "Lung (n=7)",
                        "Lung7" = "Lung (n=7)",
                        "Prostate3" = "Prostate (n=4)",
                        "Prostate4" = "Prostate (n=4)",
                        "Pancreas1" = "Pancreas (n=5)",
                        "Pancreas2" = "Pancreas (n=5)",
                        "Pancreas3" = "Pancreas (n=5)",
                        "Pancreas4" = "Pancreas (n=5)",
                        "Pancreas5" = "Pancreas (n=5)"
)


annotation_tissue <- list("Breast1" = "Breast",
                          "Breast3" = "Breast",
                          "Prostate2" = "Prostate",
                          "Ovarian3" = "Ovarian",
                          "Prostate1" = "Prostate",
                          "Colorectal5" = "Colorectal",
                          "Glioblastoma1" = "Glioblastoma",
                          "Ovarian1" = "Ovarian",
                          "Colorectal8" = "Colorectal",
                          "Ovarian5" = "Ovarian",
                          "Breast4" = "Breast",
                          "Liver5" = "Liver",
                          "Liver1" = "Liver",
                          "Liver2" ="Liver",
                          "BreastA" ="Breast",
                          "Breast9" ="Breast",
                          "Ovarian2" ="Ovarian",
                          "Ovarian4" = "Ovarian",
                          "Liver3" = "Liver",
                          "Colorectal6" = "Colorectal",
                          "Liver4" = "Liver",
                          "Colorectal7" = "Colorectal",
                          "Bladder1" = "Bladder",
                          "Bladder2" = "Bladder",
                          "Bladder3" = "Bladder",
                          "Bladder4" = "Bladder",
                          "Bladder5" = "Bladder",
                          "Kidney5" = "Kidney",
                          "Kidney1" = "Kidney",
                          "Kidney2" = "Kidney",
                          "Kidney3" = "Kidney",
                          "Kidney4" = "Kidney",
                          "Pancreas1" = "Pancreas",
                          "Pancreas2" = "Pancreas",
                          "Pancreas3" = "Pancreas",
                          "Pancreas4" = "Pancreas",
                          "Pancreas5" = "Pancreas",
                          "Glioblastoma2" = "Glioblastoma",
                          "Glioblastoma3" = "Glioblastoma",
                          "Glioblastoma4" = "Glioblastoma",
                          "Glioblastoma5" = "Glioblastoma",
                          "Colorectal1" = "Colorectal",
                          "Colorectal2" = "Colorectal",
                          "Colorectal3" = "Colorectal",
                          "Colorectal4" = "Colorectal",
                          "Breast5" = "Breast",
                          "Breast6" = "Breast",
                          "Breast7" = "Breast",
                          "Breast8" = "Breast",
                          "Lung1" = "Lung",
                          "Lung2" = "Lung",
                          "Lung3" = "Lung",
                          "Lung4" = "Lung",
                          "Lung5" = "Lung",
                          "Lung6" = "Lung",
                          "Lung7" = "Lung",
                          "Prostate3" = "Prostate",
                          "Prostate4" = "Prostate"
                          
)
