##################################################
## Project: Cancer Hallmarks
## Script purpose: Variables with metadata and full names for hallmarks and samples
## Date: 27/12/2022
## Author: Sergi Cervilla* & Mustafa Sibai*
##################################################

#Complete hallmark names
color_codes <-  list("Sustaining Proliferative Signaling"="#15CE59", 
                     "Evading Growth Suppressors" = "#701717",
                     "Avoiding Immune Destruction" = "#CB3BBD",
                     "Enabling Replicative Immortality" = "#4969D4",
                     "Tumor-Promoting Inflammation" = "#E6880D",
                     "Activating Invasion and Metastasis" = "#000000",
                     "Inducing Angiogenesis" = "#EE0F16",
                     "Genome Instability and Mutation" = "#132892",
                     "Resisting Cell Death" = "#8E909B",
                     "Deregulating Cellular Energetics" = "#71189E",
                     "Senescent cells" = "#05F3EB",
                     "Nonmutational Epigenetic reprogramming" = "#890269",
                     "Unlocking Phenotypic Plasticity" = "#95641A")
hallmark_names <- c("Sustaining Proliferative Signaling", 
                    "Evading Growth Suppressors",
                    "Avoiding Immune Destruction",
                    "Enabling Replicative Immortality",
                    "Tumor-Promoting Inflammation",
                    "Activating Invasion and Metastasis",
                    "Inducing Angiogenesis",
                    "Genome Instability and Mutation",
                    "Resisting Cell Death",
                    "Deregulating Cellular Energetics",
                    "Senescent cells",
                    "Nonmutational Epigenetic reprogramming",
                    "Unlocking Phenotypic Plasticity")

hallmark_names_list <- list("H1" = "Sustaining Proliferative Signaling", 
                       "H2" = "Evading Growth Suppressors",
                       "H3" = "Avoiding Immune Destruction",
                       "H4" = "Enabling Replicative Immortality",
                       "H5" = "Tumor-Promoting Inflammation",
                       "H6" = "Activating Invasion and Metastasis",
                       "H7" = "Inducing Angiogenesis",
                       "H8" = "Genome Instability and Mutation",
                       "H9" = "Resisting Cell Death",
                       "H10" = "Deregulating Cellular Energetics",
                       "H11" = "Senescent cells",
                       "H12" = "Nonmutational Epigenetic reprogramming",
                       "H13" = "Unlocking Phenotypic Plasticity")



annotation_method <- list("Breast" = "OCT",
                          "Ductal" = "OCT",
                          "IC" = "FFPE",
                          "Ovarian" = "OCT",
                          "Acinar" = "FFPE",
                          "Colorectal" = "OCT",
                          "Glioblastoma" = "OCT",
                          "OV4A" = "OCT",
                          #"Cervical" = "Cervix (n=1)",
                          "Intestine" = "OCT",
                          "OVFFPE" = "FFPE",
                          "DuctalFFPE" = "FFPE",
                          "ICC1L" = "FFPE",
                          "cHC1T" = "OCT",
                          "HCC1T" ="OCT",
                          "BreastA" ="OCT",
                          "TNBCA" ="OCT",
                          "CUP295" ="FFPE",
                          "CUP297" = "FFPE",
                          "CUP298" = "FFPE",
                          "CUP303" = "FFPE",
                          "CUP306" = "FFPE",
                          "CUP309" = "FFPE",
                          "CUP319" = "FFPE",
                          "CUP312" = "FFPE",
                          "CUP327" = "FFPE",
                          "CUP114B" = "FFPE",
                          "OVD1" = "FFPE",
                          "HCC2T" = "OCT",
                          "CRC1" = "OCT",
                          "HCC5D" = "OCT",
                          "CRC2" = "OCT",
                          "DU1" = "FFPE",
                          "DU2" = "FFPE",
                          "DU3" = "FFPE",
                          "DU4" = "FFPE",
                          "DU5" = "FFPE",
                          "DU6" = "FFPE",
                          "DU7" = "FFPE",
                          "DU8" = "FFPE",
                          "DU9" = "FFPE",
                          "DU10" = "FFPE",
                          "DU11" = "FFPE",
                          "DU12" = "FFPE",
                          "DU13" = "FFPE",
                          "DU14" = "FFPE",
                          "DU15" = "FFPE",
                          "DU16" = "FFPE",
                          "C2" = "FFPE",
                          "C7" = "FFPE",
                          "C20" = "FFPE",
                          "C21" = "FFPE",
                          "C34" = "FFPE",
                          "C39" = "FFPE",
                          "C45" = "FFPE",
                          "C51" = "FFPE",
                          "frozen_A1" = "OCT",
                          "frozen_A3" = "OCT",
                          "frozen_C5" = "OCT",
                          "frozen_C23" = "OCT",
                          "P259_H2A2" = "OCT",
                          "P264" = "OCT",
                          "P270" = "OCT",
                          "P288" = "OCT",
                          "P306" = "OCT",
                          "UKF242T" = "OCT",
                          "UKF260T" = "OCT",
                          "UKF269T" = "OCT",
                          "UKF275T" = "OCT",
                          "Co1" = "FFPE",
                          "Co2" = "FFPE",
                          "Co3" = "FFPE",
                          "Co4" = "FFPE",
                          "M1" = "FFPE",
                          "M2" = "FFPE",
                          "M3" = "FFPE",
                          "M4" = "FFPE",
                          "P1" = "FFPE",
                          "P3" = "FFPE",
                          "P4" = "FFPE",
                          "P5" = "FFPE",
                          "P6" = "FFPE",
                          "P7" = "FFPE",
                          "P8" = "FFPE",
                          "PC1" = "OCT",
                          "PC2" = "OCT"
                          
)


annotation_generated <- list("Breast" = "Public",
                          "Ductal" = "Public",
                          "IC" = "Public",
                          "Ovarian" = "Public",
                          "Acinar" = "Public",
                          "Colorectal" = "Public",
                          "Glioblastoma" = "Public",
                          "OV4A" = "In-House",
                          #"Cervical" = "Cervix (n=1)",
                          "Intestine" = "Public",
                          "OVFFPE" = "Public",
                          "DuctalFFPE" = "Public",
                          "ICC1L" = "Public",
                          "cHC1T" = "Public",
                          "HCC1T" ="Public",
                          "BreastA" ="Public",
                          "TNBCA" ="Public",
                          "CUP295" ="In-House",
                          "CUP297" = "Public",
                          "CUP298" = "Public",
                          "CUP303" = "Public",
                          "CUP306" = "Public",
                          "CUP309" = "Public",
                          "CUP319" = "Public",
                          "CUP312" = "Public",
                          "CUP327" = "Public",
                          "CUP114B" = "Public",
                          "OVD1" = "Public",
                          "HCC2T" = "Public",
                          "CRC1" = "Public",
                          "HCC5D" = "Public",
                          "CRC2" = "Public",
                          "DU1" = "In-House",
                          "DU2" = "In-House",
                          "DU3" = "In-House",
                          "DU4" = "In-House",
                          "DU5" = "In-House",
                          "DU6" = "In-House",
                          "DU7" = "In-House",
                          "DU8" = "In-House",
                          "DU9" = "In-House",
                          "DU10" = "In-House",
                          "DU11" = "In-House",
                          "DU12" = "In-House",
                          "DU13" = "In-House",
                          "DU14" = "In-House",
                          "DU15" = "In-House",
                          "DU16" = "In-House",
                          "C2" = "Public",
                          "C7" = "Public",
                          "C20" = "Public",
                          "C21" = "Public",
                          "C34" = "Public",
                          "C39" = "Public",
                          "C45" = "Public",
                          "C51" = "Public",
                          "frozen_A1" = "Public",
                          "frozen_A3" = "Public",
                          "frozen_C5" = "Public",
                          "frozen_C23" = "Public",
                          "P259_H2A2" = "Public",
                          "P264" = "Public",
                          "P270" = "Public",
                          "P288" = "Public",
                          "P306" = "Public",
                          "UKF242T" = "Public",
                          "UKF260T" = "Public",
                          "UKF269T" = "Public",
                          "UKF275T" = "Public",
                          "Co1" = "In-House",
                          "Co2" = "In-House",
                          "Co3" = "In-House",
                          "Co4" = "In-House",
                          "M1" = "In-House",
                          "M2" = "In-House",
                          "M3" = "In-House",
                          "M4" = "In-House",
                          "P1" = "In-House",
                          "P3" = "In-House",
                          "P4" = "In-House",
                          "P5" = "In-House",
                          "P6" = "In-House",
                          "P7" = "In-House",
                          "P8" = "In-House",
                          "PC1" = "Public",
                          "PC2" = "Public"
                          
)

annotation_site <- list("Breast" = "Breast (n=5)",
                        "Ductal" = "Breast (n=5)",
                        #"IC" = "Prostate (n=2)",
                        "Ovarian" = "Ovary (n=5)",
                        #"Acinar" = "Prostate (n=2)",
                        "Colorectal" = "Colorectal (n=4)",
                        #"Glioblastoma" = "Brain (n=1)",
                        "OV4A" = "Ovary (n=5)",
                        #"Cervical" = "Cervix (n=1)",
                        "Intestine" = "Colorectal (n=4)",
                        "OVFFPE" = "Ovary (n=5)",
                        "DuctalFFPE" = "Breast (n=5)",
                        "ICC1L" = "Liver (n=5)",
                        "cHC1T" = "Liver (n=5)",
                        "HCC1T" ="Liver (n=5)",
                        "BreastA" ="Breast (n=5)",
                        "TNBCA" ="Breast (n=5)",
                        "CUP295" ="Ovary (n=5)",
                        "CUP297" = "Omentum-CUP (n=2)",
                        "CUP298" = "Peritoneum-CUP (n=1)",
                        "CUP303" = "Skin-CUP (n=1)",
                        "CUP306" = "Bladder-CUP (n=1)",
                        "CUP309" = "Lymph node-CUP (n=3)",
                        "CUP319" = "Lymph node-CUP (n=3)",
                        "CUP312" = "Lymph node-CUP (n=3)",
                        "CUP327" = "Omentum-CUP (n=2)",
                        "CUP114B" = "Thorax-CUP (n=1)",
                        "OVD1" = "Ovary (n=5)",
                        "HCC2T" = "Liver (n=5)",
                        "CRC1" = "Colorectal (n=4)",
                        "HCC5D" = "Liver (n=5)",
                        "CRC2" = "Colorectal (n=4)",
                        "DU1" = "Bladder (n=5)",
                        "DU2" = "Bladder (n=5)",
                        "DU3" = "Bladder (n=5)",
                        "DU4" = "Bladder (n=5)",
                        "DU5" = "Bladder (n=5)",
                        "DU6" = "Bladder (n=5)",
                        "DU7" = "Bladder (n=5)",
                        "DU8" = "Bladder (n=5)",
                        "DU9" = "Bladder (n=5)",
                        "DU10" = "Bladder (n=5)",
                        "DU11" = "Bladder (n=5)",
                        "DU12" = "Bladder (n=5)",
                        "DU13" = "Bladder (n=5)",
                        "DU14" = "Bladder (n=5)",
                        "DU15" = "Bladder (n=5)",
                        "DU16" = "Bladder (n=5)",
                        "C2" = "Kidney (n=5)",
                        "C7" = "Kidney (n=5)",
                        "C20" = "Kidney (n=5)",
                        "C21" = "Kidney (n=5)",
                        "C34" = "Kidney (n=5)",
                        "C39" = "Kidney (n=5)",
                        "C45" = "Kidney (n=5)",
                        "C51" = "Kidney (n=5)",
                        "frozen_A1" = "Kidney (n=5)",
                        "frozen_A3" = "Kidney (n=5)",
                        "frozen_C5" = "Kidney (n=5)",
                        "frozen_C23" = "Kidney (n=5)",
                        "P259_H1A2" = "Pancreas (n=5)",
                        "P264" = "Pancreas (n=5)",
                        "P270" = "Pancreas (n=5)",
                        "P288" = "Pancreas (n=5)",
                        "P306" = "Pancreas (n=5)",
                        "UKF242T" = "Glioblastoma (n=5)",
                        "UKF260T" = "Glioblastoma (n=5)",
                        "UKF269T" = "Glioblastoma (n=5)",
                        "UKF275T" = "Glioblastoma (n=5)",
                        "Glioblastoma" = "Glioblastoma (n=5)",
                        "IC" = "Prostate (n=2)",
                        "Acinar" = "Prostate (n=2)"
)

sample_names <- list(Acinar = "Prostate1",
                     Breast = "Breast1",
                     BreastA = "Breast2",
                     C20 = "Kidney1",
                     C21 = "Kidney2",
                     C34 = "Kidney3",
                     C51 = "Kidney4",
                     C7 = "Kidney5",
                     cHC1T = "Liver1",
                     Co1 = "Colorectal1",
                     Co2 = "Colorectal2",
                     Co3 = "Colorectal3",
                     Co4 = "Colorectal4",
                     Colorectal = "Colorectal5",
                     CRC1 = "Colorectal6",
                     CRC2 = "Colorectal7",
                     CUP295 = "Ovarian1",
                     DU12 = "Bladder1",
                     DU13 = "Bladder2",
                     DU2 = "Bladder3",
                     DU3 = "Bladder4",
                     DU8 = "Bladder5",
                     Ductal = "Breast3",
                     DuctalFFPE = "Breast4",
                     Glioblastoma = "Glioblastoma1",
                     HCC1T = "Liver2",
                     HCC2T = "Liver3",
                     HCC5D = "Liver4",
                     IC = "Prostate2",
                     ICC1L = "Liver5",
                     Intestine = "Colorectal8",
                     M1 = "Breast5",
                     M2 = "Breast6",
                     M3 = "Breast7",
                     M4 = "Breast8",
                     OV4A = "Ovarian2",
                     Ovarian = "Ovarian3",
                     OVD1 = "Ovarian4",
                     OVFFPE = "Ovarian5",
                     P259_H2A2 = "Pancreas1",
                     P264 = "Pancreas2",
                     P270 = "Pancreas3",
                     P288 = "Pancreas4",
                     P3 = "Lung2",
                     P306 = "Pancreas5",
                     P4 = "Lung3",
                     P5 = "Lung4",
                     P6 = "Lung5",
                     P7 = "Lung6",
                     P8 = "Lung7",
                     PC1 = "Prostate3",
                     PC2 = "Prostate4",
                     TNBCA = "Breast9",
                     UKF242T = "Glioblastoma2",
                     UKF260T = "Glioblastoma3",
                     UKF269T = "Glioblastoma4",
                     UKF275T = "Glioblastoma5")


annotation_tissue <- list(Acinar = "Prostate",
               Breast = "Breast",
               BreastA = "Breast",
               C20 = "Kidney",
               C21 = "Kidney",
               C34 = "Kidney",
               C51 = "Kidney",
               C7 = "Kidney",
               cHC1T = "Liver",
               Co1 = "Colorectal",
               Co2 = "Colorectal",
               Co3 = "Colorectal",
               Co4 = "Colorectal",
               Colorectal = "Colorectal",
               CRC1 = "Colorectal",
               CRC2 = "Colorectal",
               CUP295 = "Ovary",
               DU12 = "Bladder",
               DU13 = "Bladder",
               DU2 = "Bladder",
               DU3 = "Bladder",
               DU8 = "Bladder",
               Ductal = "Breast",
               DuctalFFPE = "Breast",
               Glioblastoma = "Glioblastoma",
               HCC1T = "Liver",
               HCC2T = "Liver",
               HCC5D = "Liver",
               IC = "Prostate",
               ICC1L = "Liver",
               Intestine = "Colorectal",
               M1 = "Breast",
               M2 = "Breast",
               M3 = "Breast",
               M4 = "Breast",
               OV4A = "Ovary",
               Ovarian = "Ovary",
               OVD1 = "Ovary",
               OVFFPE = "Ovary",
               P259_H2A2 = "Pancreas",
               P264 = "Pancreas",
               P270 = "Pancreas",
               P288 = "Pancreas",
               P1 = "Lung",
               P3 = "Lung",
               P306 = "Pancreas",
               P4 = "Lung",
               P5 = "Lung",
               P6 = "Lung",
               P7 = "Lung",
               P8 = "Lung",
               PC1 = "Prostate",
               PC2 = "Prostate",
               TNBCA = "Breast",
               UKF242T = "Glioblastoma",
               UKF260T = "Glioblastoma",
               UKF269T = "Glioblastoma",
               UKF275T = "Glioblastoma")
